export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const SET_USER = 'SET_USER';
export const TOGGLE_SIDE_MENU = 'TOGGLE_SIDE_MENU';
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
